### ISSUE TITLE
Hardcoded path of python interpreter in readobjc.py

### ISSUE THREAD

**Issue by nieluj** [romainthomas/iCDump#1]
This is for version 1.1.0, installed today on macOS Ventura 13.1 using pip provided by the system installation of Python 3.9.

In readobjc.py, the interpreter is defined as such:
#!/Users/romain/x64/opt/python@3.9/bin/python3.9

It should be replaced by something more generic, like #!/usr/bin/env python3

**Comment by romainthomas** [comment]
Well actually this shebang has been overwritten by Python while generating the wheels. 

The original script actually contains the correct path: https://github.com/romainthomas/iCDump/blob/0c9878cd9c44753509651b6e2fc0c6f930083920/bindings/python/tools/readobjc.py#L1

**Comment by romainthomas** [comment]
I'll see how to fix that for the future builds

**Comment by nieluj** [comment]
understood and thanks a lot for sharing this great tool!

**Comment by nieluj** [comment]
I will close this issue since it lies in the build process and not in the source code itself
