### ISSUE TITLE
README: image is missing

### ISSUE THREAD

**Issue by cooljeanius** [romainthomas/iCDump#2]
it's just rendering with that "missing image" placeholder for me currently

**Comment by romainthomas** [comment]
That's weird, I checked on Firefox and Chrome and the image is correctly displayed. Could you attach a screenshot?

**Comment by cooljeanius** [comment]
<img width="918" alt="Screen Shot 2023-01-11 at 16 00 27" src="https://user-images.githubusercontent.com/1388660/211917104-520161f6-a006-4a1c-8c68-a1f0afe9334e.png">
btw I checked the source of the image and tried downloading it manually, and when I did, Firefox gave me the following error: 
<img width="395" alt="Screen Shot 2023-01-11 at 16 03 44" src="https://user-images.githubusercontent.com/1388660/211917494-77819251-2d43-4f67-830e-2484438ee06d.png">
...which then results in an unfinished `.webp.part` download showing up in my Downloads folder, alongside the actual image. The actual `.webp` seems to load fine in Preview, though, after I've downloaded it?

**Comment by cooljeanius** [comment]
Uh... I'm still seeing this happen?

**Comment by romainthomas** [comment]
This is actually related to your browser/setup. I checked with several os/network and it's working fine
